version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev 
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true 
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules 
      - /app/.next 
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1