version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # Use dev-specific Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true # Required for file watching in Docker
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules # Keep container's node_modules
      - /app/.next # Persist Turbopack cache
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map port 8000 on your local machine to port 8000 in the container
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
