version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 on your local machine to port 3000 in the container
    environment:
      - PORT=3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map port 8000 on your local machine to port 8000 in the container
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
